import type { Metadata } from "next";
import { NeueMontreal, EditorialNew } from "@/styles/fonts";
import "./globals.css";
import { Header } from "@/components/layout/header.tsx";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

console.log(NeueMontreal, EditorialNew)

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NeueMontreal.variable} ${EditorialNew.variable} antialiased`}
      >
          <Header />
          {children}
      </body>
    </html>
  );
}
